# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bfb37f5c43d4c60a4b2aff6d4a3eb131c9e3f6602b780dc55ecdde89d911d9b01f6c8b3666dbd7ccb03202ee11baed97f4763716ecf7466fdcf3e7a3032a50a
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://d011d848.ngrok.io
  paypal_merchant_email: stuff-facilitator@yellowtulip.it
test:
  secret_key_base: e91243c1eea186099fb0ce870b599f6e7692f675e1c878de9a5832c6feb6b33daab6c2bf12985dfda1d35422691756883f448c9c29193c579e9e65784d55378d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: http://assaggiaolio-shop.herokuapp.com
  paypal_merchant_email: info@faravetrerie.it


  # paypal_host: https://www.paypal.com
  # app_host: https://shop.assaggiaolio.com/
  # paypal_merchant_email: info@assaggiaolio.com
