require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ShippingTableRatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ShippingTableRate. As you add validations to ShippingTableRate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShippingTableRatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all shipping_table_rates as @shipping_table_rates" do
      shipping_table_rate = ShippingTableRate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:shipping_table_rates)).to eq([shipping_table_rate])
    end
  end

  describe "GET #show" do
    it "assigns the requested shipping_table_rate as @shipping_table_rate" do
      shipping_table_rate = ShippingTableRate.create! valid_attributes
      get :show, {:id => shipping_table_rate.to_param}, valid_session
      expect(assigns(:shipping_table_rate)).to eq(shipping_table_rate)
    end
  end

  describe "GET #new" do
    it "assigns a new shipping_table_rate as @shipping_table_rate" do
      get :new, {}, valid_session
      expect(assigns(:shipping_table_rate)).to be_a_new(ShippingTableRate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested shipping_table_rate as @shipping_table_rate" do
      shipping_table_rate = ShippingTableRate.create! valid_attributes
      get :edit, {:id => shipping_table_rate.to_param}, valid_session
      expect(assigns(:shipping_table_rate)).to eq(shipping_table_rate)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ShippingTableRate" do
        expect {
          post :create, {:shipping_table_rate => valid_attributes}, valid_session
        }.to change(ShippingTableRate, :count).by(1)
      end

      it "assigns a newly created shipping_table_rate as @shipping_table_rate" do
        post :create, {:shipping_table_rate => valid_attributes}, valid_session
        expect(assigns(:shipping_table_rate)).to be_a(ShippingTableRate)
        expect(assigns(:shipping_table_rate)).to be_persisted
      end

      it "redirects to the created shipping_table_rate" do
        post :create, {:shipping_table_rate => valid_attributes}, valid_session
        expect(response).to redirect_to(ShippingTableRate.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved shipping_table_rate as @shipping_table_rate" do
        post :create, {:shipping_table_rate => invalid_attributes}, valid_session
        expect(assigns(:shipping_table_rate)).to be_a_new(ShippingTableRate)
      end

      it "re-renders the 'new' template" do
        post :create, {:shipping_table_rate => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shipping_table_rate" do
        shipping_table_rate = ShippingTableRate.create! valid_attributes
        put :update, {:id => shipping_table_rate.to_param, :shipping_table_rate => new_attributes}, valid_session
        shipping_table_rate.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested shipping_table_rate as @shipping_table_rate" do
        shipping_table_rate = ShippingTableRate.create! valid_attributes
        put :update, {:id => shipping_table_rate.to_param, :shipping_table_rate => valid_attributes}, valid_session
        expect(assigns(:shipping_table_rate)).to eq(shipping_table_rate)
      end

      it "redirects to the shipping_table_rate" do
        shipping_table_rate = ShippingTableRate.create! valid_attributes
        put :update, {:id => shipping_table_rate.to_param, :shipping_table_rate => valid_attributes}, valid_session
        expect(response).to redirect_to(shipping_table_rate)
      end
    end

    context "with invalid params" do
      it "assigns the shipping_table_rate as @shipping_table_rate" do
        shipping_table_rate = ShippingTableRate.create! valid_attributes
        put :update, {:id => shipping_table_rate.to_param, :shipping_table_rate => invalid_attributes}, valid_session
        expect(assigns(:shipping_table_rate)).to eq(shipping_table_rate)
      end

      it "re-renders the 'edit' template" do
        shipping_table_rate = ShippingTableRate.create! valid_attributes
        put :update, {:id => shipping_table_rate.to_param, :shipping_table_rate => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested shipping_table_rate" do
      shipping_table_rate = ShippingTableRate.create! valid_attributes
      expect {
        delete :destroy, {:id => shipping_table_rate.to_param}, valid_session
      }.to change(ShippingTableRate, :count).by(-1)
    end

    it "redirects to the shipping_table_rates list" do
      shipping_table_rate = ShippingTableRate.create! valid_attributes
      delete :destroy, {:id => shipping_table_rate.to_param}, valid_session
      expect(response).to redirect_to(shipping_table_rates_url)
    end
  end

end
